"""Observation models A-D for experiment P2-FR2 (unknown full-data law).

Unknowns are the joint masses p(c, r) = P(C = c, R = r) (natural mask R).
Labels are observed only for complete cases (assumption L1: S = 1 iff
R = 1...1; S is the label-availability indicator).  The observable
information differs by setting:

  A  "oracle_w":      C-information plus the full-data law w_c = sum_r p(c,r).
  B  "cc_only":       only the complete-case conditional v_c = P(C=c | R=1...1).
  C  "cc_plus_unlab": one i.i.d. sample; theta_c = P(C=c, R=1...1) for complete
                      cases and P(R=r, X_r=o) for incomplete masks (this also
                      fixes the mask frequencies rho_r).
  D  "conditionals":  v_c and mu_r(o) = P(X_r=o | R=r) from separate samples;
                      the selection fractions rho_r are unknown.

Sensitivity model M_cc(Gamma) (pattern-mixture form relative to complete cases):
for every incomplete mask r there is a scale b_r >= 0 with
      b_r kappa_c / Gamma <= p(c, r) <= Gamma b_r kappa_c   for all cells c,
where kappa_c is a KNOWN constant proportional to the complete-case law
(kappa = v in B/D, kappa = theta in A/C).  Equivalently the likelihood ratio
P(c | R=r) / P(c | R=complete) varies across cells by at most Gamma^2.
Gamma = 1 means every mask has the complete-case full-data law (MCAR).

Linearity: in B/D the complete-case rows are p(c, 1) = rho_1 v_c with rho_1 an
unknown scalar; the model's scale is lambda_r * rho_1, a product of unknowns,
which is replaced by the single free variable b_r.  This is an exact
reformulation because lambda_r appears nowhere else and rho_1 > 0 (see
RESEARCH_PACKET.md, FR2 notes).  No unknown product is plugged in.

gamma options: a Fraction >= 1; "SUPPORT_ONLY" (p(c,r) = 0 where kappa_c = 0,
nothing else -- the closure of the Gamma -> infinity limit); "NO_MODEL" (no
restriction at all, Manski-type).  SUPPORT_ONLY and NO_MODEL differ exactly
when the complete-case support misses a cell.

For finite samples, ``theta_box`` gives lower/upper values for every
observable cell probability (setting C only); constraints are relaxed to an
outer linear set (see ``outer`` notes in build()).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from fractions import Fraction
from typing import Dict, List, Optional, Tuple

from .exact_lp import solve_lp
from .finite_model import FiniteJoint, Pattern, Policy, all_x, observe

Q = Fraction
SETTINGS = ("A_oracle_w", "B_cc_only", "C_cc_plus_unlab", "D_conditionals")


@dataclass
class Truth:
    """Population quantities generated by (w, pi*)."""
    joint: FiniteJoint
    p: Dict[Tuple, Fraction]           # p(c, r)
    full: Pattern
    rho: Dict[Pattern, Fraction]
    theta: Dict[Tuple, Fraction]       # P(C=c, R=full)
    v: Dict[Tuple, Fraction]           # P(C=c | R=full)
    obs: Dict[Tuple[Pattern, Tuple], Fraction]   # P(R=r, X_r=o), r != full
    mu: Dict[Tuple[Pattern, Tuple], Fraction]    # P(X_r=o | R=r)


def truth_from_policy(joint: FiniteJoint, pi: Policy) -> Truth:
    full = tuple([1] * joint.d)
    p = {(c, r): joint.prob[c] * pi[c][r] for c in joint.cells() for r in joint.patterns()}
    rho = {r: sum((p[(c, r)] for c in joint.cells()), Q(0)) for r in joint.patterns()}
    if rho[full] == 0:
        raise ValueError("no complete cases: v undefined")
    theta = {c: p[(c, full)] for c in joint.cells()}
    v = {c: theta[c] / rho[full] for c in joint.cells()}
    obs, mu = {}, {}
    for r in joint.patterns():
        if r == full:
            continue
        for x in all_x(joint.d, joint.levels):
            obs.setdefault((r, observe(x, r)), Q(0))
        for c in joint.cells():
            obs[(r, observe(c[0], r))] += p[(c, r)]
        for key in [k for k in obs if k[0] == r]:
            mu[key] = obs[key] / rho[r] if rho[r] else Q(0)
    return Truth(joint, p, full, rho, theta, v, obs, mu)


def gamma_cc_squared(t: Truth) -> Optional[Fraction]:
    """Smallest Gamma^2 such that p* satisfies M_cc(Gamma); None = infinite."""
    worst = Q(1)
    for r in t.joint.patterns():
        if r == t.full:
            continue
        ratios = []
        for c in t.joint.cells():
            if t.v[c] == 0:
                if t.p[(c, r)] > 0:
                    return None  # support violation
                continue
            ratios.append(t.p[(c, r)] / t.v[c])
        if not ratios or max(ratios) == 0:
            continue
        if min(ratios) == 0:
            return None
        worst = max(worst, max(ratios) / min(ratios))
    return worst


@dataclass
class Built:
    names: List[str]
    A: List[List[Fraction]]
    b: List[Fraction]
    lower: List[Fraction]
    upper: List[Fraction]
    pexpr: Dict[Tuple, Dict[int, Fraction]]   # p(c,r) as affine map of variables
    notes: List[str] = field(default_factory=list)


class _B:
    def __init__(self):
        self.names, self.lower, self.upper = [], [], []
        self.rows: List[Tuple[Dict[int, Fraction], Fraction]] = []

    def var(self, name, lo, up):
        self.names.append(name)
        self.lower.append(Q(lo))
        self.upper.append(Q(up))
        return len(self.names) - 1

    def row(self, coefs: Dict[int, Fraction], rhs):
        self.rows.append((coefs, Q(rhs)))


def _add(dst, src, scale=Q(1)):
    for k, v in src.items():
        dst[k] = dst.get(k, Q(0)) + scale * v


def build(t: Truth, setting: str, gamma, theta_box=None, obs_box=None) -> Built:
    """Linear system for the identified set of p under (setting, gamma).

    theta_box / obs_box (setting C only): dicts of (lo, hi) for the observable
    probabilities.  With boxes the Gamma rows use kappa_lo in the lower and
    kappa_hi in the upper inequality, an outer relaxation of the bilinear
    constraint b_r * p(c, full) (valid whenever the true values are in the box).
    """
    if setting not in SETTINGS:
        raise ValueError(setting)
    J = t.joint
    cells, full = J.cells(), t.full
    inc = [r for r in J.patterns() if r != full]
    B = _B()
    pexpr: Dict[Tuple, Dict[int, Fraction]] = {}

    # --- complete-case block and kappa
    if setting in ("B_cc_only", "D_conditionals"):
        if theta_box is not None:
            raise ValueError("finite-sample boxes implemented for setting C/A only")
        rho1 = B.var("rho_full", 0, 1)
        klo = khi = t.v
        for c in cells:
            j = B.var(f"p{c}{full}", 0, 1)
            pexpr[(c, full)] = {j: Q(1)}
            B.row({j: Q(1), rho1: -t.v[c]}, 0)
    else:
        if theta_box is None:
            klo = khi = t.theta
            tb = {c: (t.theta[c], t.theta[c]) for c in cells}
        else:
            tb = theta_box
            klo = {c: tb[c][0] for c in cells}
            khi = {c: tb[c][1] for c in cells}
        for c in cells:
            j = B.var(f"p{c}{full}", tb[c][0], tb[c][1])
            pexpr[(c, full)] = {j: Q(1)}

    # --- incomplete masks under the sensitivity model
    sum_klo = sum(klo.values())
    for r in inc:
        if gamma in ("NO_MODEL", "SUPPORT_ONLY"):
            for c in cells:
                up = Q(0) if (gamma == "SUPPORT_ONLY" and khi[c] == 0) else Q(1)
                j = B.var(f"p{c}{r}", 0, up)
                pexpr[(c, r)] = {j: Q(1)}
            continue
        g = Q(gamma)
        if sum_klo == 0:
            # Every kappa_lo is 0 (e.g. an outer box whose lower ends are all 0,
            # or n_complete = 0).  The lower Gamma inequality is then vacuous and
            # b_r is unbounded, so the exact projection of the relaxed set onto p
            # is the support restriction p(c, r) = 0 where kappa_hi = 0.
            # Empirical zeros (kappa_lo = 0 < kappa_hi) are NOT fixed at zero.
            for c in cells:
                up = Q(0) if khi[c] == 0 else Q(1)
                j = B.var(f"p{c}{r}", 0, up)
                pexpr[(c, r)] = {j: Q(1)}
            continue
        bmax = g / sum_klo
        bj = B.var(f"b{r}", 0, bmax)
        tmax = g * max(khi.values()) * bmax + 1
        for c in cells:
            sj = B.var(f"s{c}{r}", 0, 1)
            tj = B.var(f"t{c}{r}", 0, tmax)
            # p = (klo/g) b + s ;  s + t = (g khi - klo/g) b
            pexpr[(c, r)] = {bj: klo[c] / g, sj: Q(1)}
            B.row({sj: Q(1), tj: Q(1), bj: -(g * khi[c] - klo[c] / g)}, 0)

    # --- total mass
    tot: Dict[int, Fraction] = {}
    for key in pexpr:
        _add(tot, pexpr[key])
    B.row(tot, 1)

    # --- unlabelled information
    groups: Dict[Tuple, List] = {}
    for r in inc:
        for c in cells:
            groups.setdefault((r, observe(c[0], r)), []).append(c)
    if setting in ("A_oracle_w", "C_cc_plus_unlab"):
        for (r, o), cs in groups.items():
            row: Dict[int, Fraction] = {}
            for c in cs:
                _add(row, pexpr[(c, r)])
            if obs_box is None:
                B.row(row, t.obs[(r, o)])
            else:
                lo, hi = obs_box[(r, o)]
                e = B.var(f"e{r}{o}", lo, hi)
                row[e] = row.get(e, Q(0)) - 1
                B.row(row, 0)
    elif setting == "D_conditionals":
        rho_r = {r: B.var(f"rho{r}", 0, 1) for r in inc}
        for (r, o), cs in groups.items():
            row = {}
            for c in cs:
                _add(row, pexpr[(c, r)])
            row[rho_r[r]] = row.get(rho_r[r], Q(0)) - t.mu[(r, o)]
            B.row(row, 0)
    if setting == "A_oracle_w":
        if obs_box is not None:
            raise ValueError("oracle setting is population-only")
        for c in cells:
            row = {}
            for r in J.patterns():
                _add(row, pexpr[(c, r)])
            B.row(row, J.prob[c])

    n = len(B.names)
    A = []
    for coefs, _ in B.rows:
        dense = [Q(0)] * n
        for k, v in coefs.items():
            dense[k] += v
        A.append(dense)
    return Built(B.names, A, [rhs for _, rhs in B.rows], B.lower, B.upper, pexpr)


def objective(built: Built, table) -> List[Fraction]:
    c = [Q(0)] * len(built.names)
    for (cell, r), expr in built.pexpr.items():
        coef = table[(cell, r)]
        if coef:
            for k, v in expr.items():
                c[k] += coef * v
    return c


@dataclass
class Iv:
    status: str
    lo: Optional[Fraction] = None
    hi: Optional[Fraction] = None
    certified: bool = False
    iterations: int = 0

    def contains(self, x):
        return None if self.status != "OPTIMAL" else self.lo <= x <= self.hi

    def decision(self):
        if self.status != "OPTIMAL":
            return "infeasible"
        return "A_better" if self.hi < 0 else ("B_better" if self.lo > 0 else "undetermined")


def interval(built: Built, table) -> Iv:
    c = objective(built, table)
    lo = solve_lp(c, built.A, built.b, built.lower, built.upper, "min")
    if lo.status != "OPTIMAL":
        return Iv("INFEASIBLE", certified=lo.certificate_ok, iterations=lo.iterations)
    hi = solve_lp(c, built.A, built.b, built.lower, built.upper, "max")
    return Iv("OPTIMAL", lo.value, hi.value, lo.certificate_ok and hi.certificate_ok,
              lo.iterations + hi.iterations)


def truth_in_model(t: Truth, gamma) -> bool:
    """Does p* satisfy the sensitivity/support part of the model?  (The
    information constraints hold for p* by construction.)"""
    if gamma == "NO_MODEL":
        return True
    if gamma == "SUPPORT_ONLY":
        return all(t.p[(c, r)] == 0 for c in t.joint.cells() for r in t.joint.patterns()
                   if r != t.full and t.v[c] == 0)
    g2 = gamma_cc_squared(t)
    return g2 is not None and g2 <= Q(gamma) ** 2


def truth_value(t: Truth, table) -> Fraction:
    return sum((t.p[k] * table[k] for k in t.p), Q(0))


# ---------------------------------------------------------------------------
# Sign interpretation with endpoint attainment (added in the v2 correction)
# ---------------------------------------------------------------------------

def endpoint_attained(built: Built, table, value: Fraction) -> Optional[bool]:
    """Is the endpoint `value` reached by a *valid* probability model?

    Valid means rho_full > 0 (complete cases exist, so v is a conditional law).
    In settings A/C rho_full is fixed by the data and every LP point is valid,
    so None ("not applicable": attained) is returned.  Otherwise solve
    max rho_full s.t. feasibility and objective == value; attained iff > 0.
    """
    if "rho_full" not in built.names:
        return None
    j = built.names.index("rho_full")
    c = objective(built, table)
    A = built.A + [c]
    b = built.b + [Q(value)]
    e = [Q(0)] * len(built.names)
    e[j] = Q(1)
    res = solve_lp(e, A, b, built.lower, built.upper, "max")
    if res.status != "OPTIMAL" or not res.certificate_ok:
        raise RuntimeError("attainment LP failed")
    return res.value > 0


def classify_sign(lo, hi, lo_attained=True, hi_attained=True) -> str:
    """Interpretation of an identified interval for Delta = R_A - R_B.

    STRICT_A / STRICT_B : every compatible law has the sign, with margin
                          min(|lo|,|hi|) > 0 (A better means Delta < 0).
    WEAK_A / WEAK_B     : one endpoint is exactly 0 and attained: the model
                          is never worse, a tie is compatible with the data.
    A_NO_MARGIN / B_NO_MARGIN : the 0 endpoint is reached only in the closure
                          (e.g. rho_full -> 0): strict for every valid law,
                          but without a uniform margin.
    BOTH_ORDERS         : lo < 0 < hi; both strict orders are compatible
                          (interior values are always attained).
    TIE                 : lo = hi = 0.
    """
    if lo is None:
        return "INFEASIBLE"
    if hi < 0:
        return "STRICT_A"
    if lo > 0:
        return "STRICT_B"
    if lo == 0 and hi == 0:
        return "TIE"
    if hi == 0:
        return "WEAK_A" if hi_attained is not False else "A_NO_MARGIN"
    if lo == 0:
        return "WEAK_B" if lo_attained is not False else "B_NO_MARGIN"
    return "BOTH_ORDERS"


def solve_endpoint(built: Built, table, sense: str):
    """Exact LP endpoint together with its primal solution."""
    res = solve_lp(objective(built, table), built.A, built.b, built.lower, built.upper, sense)
    return res


def recover_model(t: Truth, built: Built, x, gamma):
    """Reverse map of the b_r reparametrisation for an LP point x.

    Returns (status, info).  status is
      "PROBABILITY_MODEL" : p is a joint law with rho_full > 0, v = p(.,full)/rho_full
                            is the complete-case law, and for every incomplete
                            mask with rho_r > 0, lambda_r = b_r/rho_r (b_r * s_full /
                            rho_r when kappa = theta) satisfies the ratio bounds of
                            M_cc(Gamma) including absolute continuity;
      "CLOSURE_ONLY"      : rho_full = 0 (no complete cases): not a valid model,
                            only a limit of valid models;
      "VIOLATION"         : any check failed (would indicate a bug).
    """
    J = t.joint
    p = {}
    for key, expr in built.pexpr.items():
        p[key] = sum((x[k] * v for k, v in expr.items()), Q(0))
    if any(v < 0 for v in p.values()) or sum(p.values()) != 1:
        return "VIOLATION", {"reason": "not a probability law"}
    full = t.full
    rho = {r: sum((p[(c, r)] for c in J.cells()), Q(0)) for r in J.patterns()}
    if rho[full] == 0:
        return "CLOSURE_ONLY", {"rho_full": "0"}
    v = {c: p[(c, full)] / rho[full] for c in J.cells()}
    if gamma in ("NO_MODEL",):
        return "PROBABILITY_MODEL", {}
    for r in J.patterns():
        if r == full or rho[r] == 0:
            continue
        ratios = []
        for c in J.cells():
            cond = p[(c, r)] / rho[r]
            if v[c] == 0:
                if cond > 0:
                    return "VIOLATION", {"reason": f"absolute continuity fails at {c},{r}"}
                continue
            ratios.append(cond / v[c])
        if gamma == "SUPPORT_ONLY":
            continue
        if min(ratios) == 0 or max(ratios) / min(ratios) > Q(gamma) ** 2:
            return "VIOLATION", {"reason": f"ratio spread exceeds Gamma^2 at mask {r}"}
    return "PROBABILITY_MODEL", {"rho_full": str(rho[full])}
