"""Generate LaTeX tables/figure data for paper/ from results/raw (no recomputation).

    python3 scripts/make_paper_tables.py
Writes paper/generated/*.tex.  Every number is read from a raw JSON file.
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "results", "raw")
OUT = os.path.join(ROOT, "paper", "generated")


def load(name):
    with open(os.path.join(RAW, name)) as f:
        return json.load(f)


def v(x, nd=4):
    return "--" if x is None else f"{x['float']:+.{nd}f}"


def iv(lo, hi, nd=4):
    if lo is None:
        return "infeasible"
    return f"[{v(lo, nd)}, {v(hi, nd)}]"


def dec(d):
    return {"A_better": "A", "B_better": "B", "undetermined": "?", "infeasible": "$\\emptyset$"}.get(d, d)


def write(name, text):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), "w") as f:
        f.write("% generated by scripts/make_paper_tables.py from results/raw; do not edit\n" + text)


def fr1_table():
    B = load("p2_fr1_B_intervals.json")
    E = load("p2_fr1_E_gamma_star.json")
    rows = {(r["gamma"], r["kind"]): r for r in B["rows"]}
    lines = [r"\begin{tabular}{llll}", r"\toprule",
             r"$\Gamma$ & joint interval & separate interval & scenario grid in set \\", r"\midrule"]
    for g in ["5/4", "3/2", "2", "3"]:
        r = rows[(g, "pattern")]
        j, s = r["joint"], r["separate"]
        sg = r["scenario_grid_in_set"]
        lines.append(f"{g} & {iv(j['lo'], j['hi'])} ({dec(j['sign_decision'])}) & "
                     f"{iv(s['lo'], s['hi'])} ({dec(s['sign_decision'])}) & "
                     f"{iv(sg[0], sg[1]) if sg else '--'} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("tab_fr1_intervals.tex", "\n".join(lines) + "\n")
    gs = E["gamma_star"]
    parts = []
    for k, name in [("none", "no constraint"), ("feature", "feature rates"), ("pattern", "pattern rates"),
                    ("observed_law", "unlabelled law")]:
        parts.append(f"{name} & ({gs[k]['bracket_lo_excludes_0']['float']:.4f}, {gs[k]['bracket_hi_contains_0']['float']:.4f}] \\\\")
    body = [r"\begin{tabular}{ll}", r"\toprule", r"information (FR1 model, $w$ known) & $\Gamma^*$ bracket \\", r"\midrule"]
    body += parts + [f"closed form $\\Gamma_{{cf}}$ (pattern) & {E['gamma_closed_form_pattern']['float']:.4f} \\\\",
                     r"\bottomrule", r"\end{tabular}"]
    write("tab_fr1_gammastar.tex", "\n".join(body) + "\n")


SET_NAMES = {"A_oracle_w": "A (oracle $w$)", "B_cc_only": "B (complete cases)",
             "C_cc_plus_unlab": "C (B + masks + unlabelled)", "D_conditionals": "D (conditionals, $\\rho$ unknown)"}


CAT = {"STRICT_A": "A$^{s}$", "STRICT_B": "B$^{s}$", "WEAK_A": "A$^{w}$", "WEAK_B": "B$^{w}$",
       "A_NO_MARGIN": "A$^{0}$", "B_NO_MARGIN": "B$^{0}$", "BOTH_ORDERS": "$\\pm$", "TIE": "=",
       "INFEASIBLE": "$\\emptyset$", "EMPTY_VALID": "$\\emptyset^{c}$"}


def validity():
    """v4.1: rows of settings B/D whose VALID set is empty (eta_max = 0 over the
    whole LP set; results/derived/p2_validity_eta.json).  For them the LP
    interval is only a closure artefact and the category is EMPTY_VALID."""
    path = os.path.join(ROOT, "results", "derived", "p2_validity_eta.json")
    if not os.path.exists(path):
        return {}
    return {(r["source"], r["setting"], r["gamma_cc"]): r["valid_set"] for r in json.load(open(path))["rows"]}


def reclass():
    """v3: A/C categories from the v2 re-aggregation; B/D categories from the
    PILOT2 eta check (all definition-required rho > 0), which supersedes v2's
    rho_full-only attainment check for D."""
    path = os.path.join(ROOT, "results", "derived", "p2_sign_reclassification.json")
    with open(path) as f:
        out = {(r["setting"], r["gamma_cc"]): r for r in json.load(f)["fr2_primary"]}
    p2 = os.path.join(RAW, "p2_pilot2_results.json")
    if os.path.exists(p2):
        for r in json.load(open(p2))["D_endpoint"]["rows"]:
            k = (r["setting"], r["gamma_cc"])
            out[k] = dict(out[k], category=r["category"],
                          lo_attained=r["eta_lo"]["float"] > 0, hi_attained=r["eta_hi"]["float"] > 0)
    for (src, st, g), vv in validity().items():
        if src == "P2-FR2:E0_MCAR" and vv == "EMPTY" and (st, g) in out:
            out[(st, g)] = dict(out[(st, g)], category="EMPTY_VALID")
    return out


def fr2_primary():
    B = load("p2_fr2_B_primary.json")
    rc = reclass()
    rows = {(r["setting"], r["gamma"]): r for r in B["rows"]}
    gammas = ["1", "3/2", "2", "NO_MODEL"]
    head = " & ".join(["setting"] + [("no model" if g == "NO_MODEL" else f"$\\Gamma_{{cc}}={g}$") for g in gammas])
    lines = [r"\begin{tabular}{l" + "l" * len(gammas) + "}", r"\toprule", head + r" \\", r"\midrule"]
    for s in ["A_oracle_w", "C_cc_plus_unlab", "D_conditionals", "B_cc_only"]:
        cells = []
        for g in gammas:
            j = rows[(s, g)]["joint"]
            r = rc[(s, g)]
            star = "$^{\\dagger}$" if (r["lo_attained"] is False or r["hi_attained"] is False) else ""
            cells.append(f"{iv(j['lo'], j['hi'], 3)}{star} {CAT[r['category']]}")
        lines.append(SET_NAMES[s] + " & " + " & ".join(cells) + r" \\")
    lines += [r"\midrule"]
    for s in ["A_oracle_w", "C_cc_plus_unlab", "B_cc_only"]:
        cells = []
        for g in gammas:
            r = rows[(s, g)]
            cells.append("--" if r["separate_over_joint_width"] is None else f"{r['separate_over_joint_width']:.2f}")
        lines.append("sep./joint width, " + s[0] + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("tab_fr2_primary.tex", "\n".join(lines) + "\n")
    # figure coordinates (numeric Gamma only)
    fig = []
    for s, style in [("A_oracle_w", "densely dotted"), ("C_cc_plus_unlab", "solid"), ("B_cc_only", "dashed")]:
        for end in ("lo", "hi"):
            pts = []
            for g, x in [("1", 1), ("5/4", 1.25), ("3/2", 1.5), ("2", 2), ("3", 3)]:
                pts.append(f"({x},{rows[(s, g)]['joint'][end]['float']:.5f})")
            fig.append(f"\\addplot[{style}, mark=none] coordinates {{{' '.join(pts)}}};")
    write("fig_fr2_intervals_coords.tex", "\n".join(fig) + "\n")


def fr2_truths():
    A = load("p2_fr2_A_truths.json")["truths"]
    lines = [r"\begin{tabular}{lrrrr}", r"\toprule",
             r"environment & $\Gamma_{cc}$ & $\Delta_{\mathrm{nat}}$ (oracle) & dropout on complete cases & dropout on population \\",
             r"\midrule"]
    for e, s in A.items():
        g = "$\\infty$" if s["gamma_cc_float"] is None else f"{s['gamma_cc_float']:.2f}"
        lines.append(f"\\texttt{{{e.replace('_', chr(92) + '_')}}} & {g} & {v(s['oracle_delta_nat'])} & "
                     f"{v(s['complete_case_dropout_delta_q'])} & {v(s['population_dropout_delta_q'])} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("tab_fr2_truths.tex", "\n".join(lines) + "\n")


def fr2_finite():
    F = load("p2_fr2_F_finite_sample.json")["rows"]
    lines = [r"\begin{tabular}{rrlll}", r"\toprule",
             r"$n$ & $\Gamma$ & plug-in (draw 1 / draw 2) & outer 95\% CI (draw 1) & population \\", r"\midrule"]
    by = {}
    for r in F:
        by.setdefault((r["n"], r["gamma"]), []).append(r)
    for (n, g), rs in sorted(by.items(), key=lambda t: (t[0][0], t[0][1])):
        pl = " / ".join(("infeas." if r["plug_in"]["status"] != "OPTIMAL" else dec(r["plug_in"]["decision"])) for r in rs)
        o, p = rs[0]["outer_ci"], rs[0]["population"]
        lines.append(f"{n} & {g} & {pl} & {iv(o['lo'], o['hi'], 3)} {dec(o['decision'])} & {iv(p['lo'], p['hi'], 3)} {dec(p['decision'])} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("tab_fr2_finite.tex", "\n".join(lines) + "\n")


def audit_tables():
    G = load("p2_fr2_G_criterion_audit.json")["rows"]
    lines = [r"\begin{tabular}{lllll}", r"\toprule",
             r"set & $\Gamma$ & width $=0$ & explicit row space & general criterion \\", r"\midrule"]
    for r in G:
        lines.append(f"{r['set'].replace('_', chr(92) + '_')} & {r['gamma']} & {r['width_zero']} & {r['explicit_rowspace_test']} & {r['general_test']} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("tab_fr2_audit.tex", "\n".join(lines) + "\n")
    Z = load("p2_fr2_E_structural_zero.json")["rows"]
    lines = [r"\begin{tabular}{lllll}", r"\toprule", r"setting & model & interval & $p^*$ in model & truth in interval \\", r"\midrule"]
    for r in Z:
        i = r["interval"]
        lines.append(f"{r['setting'][0]} & {r['gamma'].replace('_', ' ')} & {iv(i['lo'], i['hi'], 3)} & {r['truth_in_model']} & {r['oracle_contained']} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("tab_fr2_support.tex", "\n".join(lines) + "\n")


def pilot():
    path = os.path.join(RAW, "p2_pilot_results.json")
    if not os.path.exists(path):
        write("tab_pilot.tex", "% P2-PILOT1 NOT RUN\n")
        return
    d = json.load(open(path))
    lines = [r"\begin{tabular}{lrrrrl}", r"\toprule",
             r"mask rule & $n$ (complete) & held-out $\Dnat$ & complete-case dropout & realised $\Gamma_{cc}$ & agree? \\", r"\midrule"]
    for m, r in d["results"].items():
        h, c = r["held_out_delta_uses_hidden_labels"]["float"], r["complete_case_dropout_delta"]["float"]
        g2 = r["gamma_cc_squared_of_realised_population"]
        g = "$\\infty$" if g2 is None else f"{g2['float'] ** 0.5:.2f}"
        lines.append(f"{m.replace('_', ' ')} & {r['n_eval_units']} ({r['n_complete']}) & {h:+.4f} & {c:+.4f} & {g} & {'yes' if (h < 0) == (c < 0) else 'no'} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("tab_pilot_summary.tex", "\n".join(lines) + "\n")
    gl = ["1", "5/4", "3/2", "2", "3", "NO_MODEL"]
    lines = [r"\begin{tabular}{ll" + "l" * len(gl) + "}", r"\toprule",
             "mask rule & set & " + " & ".join(("no model" if g == "NO_MODEL" else f"$\\Gamma_{{cc}}={g}$") for g in gl) + r" \\", r"\midrule"]
    for m, r in d["results"].items():
        for kind, rows in (("identified", r["identified"]), ("outer 95\\%", r["outer_ci"])):
            byg = {x["gamma_cc"]: x for x in rows}
            cells = []
            for g in gl:
                x = byg.get(g)
                cells.append("--" if x is None else (f"{iv(x['lo'], x['hi'], 3)} {CAT[x['category']]}" if x["status"] == "OPTIMAL" else CAT["INFEASIBLE"]))
            lines.append(f"{m.split('_')[1]} & {kind} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("tab_pilot_intervals.tex", "\n".join(lines) + "\n")


INF = "$\\infty$"


def pilot_compare():
    p2 = os.path.join(RAW, "p2_pilot2_results.json")
    if not os.path.exists(p2):
        return
    d = json.load(open(p2))["expected_mask_comparison"]
    gl = ["1", "5/4", "3/2", "2", "NO_MODEL"]
    head = " & ".join(["mask rule", "law", "true $\\Dnat$", "cc dropout", "$\\Gamma_{cc}$"] +
                      [("no model" if g == "NO_MODEL" else f"$\\Gamma_{{cc}}={g}$") for g in gl])
    lines = [r"\begin{tabular}{lll" + "r" * 2 + "l" * len(gl) + "}", r"\toprule", head + r" \\", r"\midrule"]
    for m, c in d.items():
        name = "MNAR" if "mnar" in m else "MCAR"
        byg = {x["gamma_cc"]: x for x in c["C_identified_from_expected_observables"]}
        cells = [CAT[byg[g]["category"]] if byg[g]["status"] == "OPTIMAL" else CAT["INFEASIBLE"] for g in gl]
        g = c["expected_gamma_cc_free_scale"]
        gs = INF if g is None else f"{g:.2f}"
        lines.append(f"{name} & expected & {v(c['A_expected_true_delta'])} & {v(c['B_expected_cc_dropout'])} & "
                     f"{gs} & " + " & ".join(cells) + r" \\")
        r = c["D_pilot1_realised"]
        byg = {x["gamma_cc"]: x for x in r["identified"]}
        cells = [CAT[byg[g]["category"]] if byg[g]["status"] == "OPTIMAL" else CAT["INFEASIBLE"] for g in gl]
        g2 = r["realised_gamma_cc_squared"]
        gs = INF if g2 is None else f"{g2['float'] ** 0.5:.2f}"
        lines.append(f" & realised & {v(r['held_out_delta'])} & {v(r['cc_dropout'])} & "
                     f"{gs} & " + " & ".join(cells) + r" \\")
        byg = {x["gamma_cc"]: x for x in r["outer_ci"]}
        cells = [(CAT[byg[g]["category"]] if byg[g]["status"] == "OPTIMAL" else CAT["INFEASIBLE"]) if g in byg else "--" for g in gl]
        lines.append(" & outer 95\\% & & & & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("tab_pilot_compare.tex", "\n".join(lines) + "\n")


def clean1_table():
    p = os.path.join(RAW, "p2_clean1_results.json")
    if not os.path.exists(p):
        return
    d = json.load(open(p))["expected_mask"]
    val = validity()
    gl = ["1", "5/4", "3/2", "2", "NO_MODEL"]
    head = " & ".join(["mask rule", "setting", "true $\\Delta$", "cc dropout"] +
                      [("no model" if g == "NO_MODEL" else f"$\\Gamma_{{cc}}={g}$") for g in gl])
    lines = [r"\begin{tabular}{llrr" + "l" * len(gl) + "}", r"\toprule", head + r" \\", r"\midrule"]
    for m, c in d.items():
        name = "MNAR" if "mnar" in m else "MCAR"
        first = True
        for st, lab in (("C_cc_plus_unlab", "C"), ("D_conditionals", "D"), ("B_cc_only", "B")):
            byg = {x["gamma_cc"]: x for x in c["settings"][st]}
            cells = [CAT["EMPTY_VALID"] if val.get((f"P2-PILOT-CLEAN1:{m}", st, g)) == "EMPTY" else CAT[byg[g]["category"]] for g in gl]
            lead = f"{name} & {lab} & {v(c['expected_true_delta_oracle'])} & {v(c['expected_cc_dropout_delta'])}" if first else f" & {lab} & & "
            lines.append(lead + " & " + " & ".join(cells) + r" \\")
            first = False
    lines += [r"\bottomrule", r"\end{tabular}"]
    write("tab_clean1.tex", "\n".join(lines) + "\n")


if __name__ == "__main__":
    clean1_table()
    pilot_compare()
    pilot()
    fr1_table()
    fr2_primary()
    fr2_truths()
    fr2_finite()
    audit_tables()
    print("written:", sorted(os.listdir(OUT)))
